### ISSUE TITLE
Deleting objects should delete references

### ISSUE THREAD

**Issue by IsmAvatar** [IsmAvatar/LateralGM#122]
This ticket covers a lot of ground, as it contains items that are bugs and items that are features, but all should be completed before this story is satisfactory.

Currently if an object is deleted, it will not delete its references, such as instances and outside events. This is not ideal.

Use case 1: A user deletes an object with no references. Should confirm deletion and delete.
Use case 2: A user deletes an object with references in rooms (called instances). Should confirm deletion of both object AND instances, and delete the object and its instances.
Use case 3: A user deletes an object with references in events of other objects (such as collision). Should confirm deletion of both object AND events, and then delete the object and those events.

Additional case: An object has not been deleted, but an object has some events referencing a non-existent object or a room has some instances referencing a non-existent object - called orphans. These orphans should be maintained and visible, as they are valuable to a user. They should only be cleaned up if the user requests it, or if necessary for some other feature (such as compiling), in which case they should either be temporarily cleaned for that feature, or if it must be permanent, the user should be alerted. While implementing this ticket, please preserve this behavior.

This ticket is open for discussion, but can be implemented as described.

**Comment by RobertBColton** [comment]
Now that I've actually read this ticket. @IsmAvatar Consider that people are still relying on LGM to open corrupted GM files, only sometimes met with better success than GM's IDE. I would be much happier with a dialog at load with something akin to cleaning up backup files, such as "123 orphaned references could not be determined, would you like to clear them?"

As far as what @JoshDreamland I don't see it as much of an issue.
When the room loads or an instance is created it says "hey object, I have a reference to you" and the object doesn't care that it's a room and has no idea what a room is, but the room does need to know what an object is, which is expected. When you delete the object it pops back a message "hey you guys I'm being deleted so you should clear your reference to me"

**Comment by RobertBColton** [comment]
This problem has come back to bite us in #297 with the GMX writer. I did not consider that LGM leave's dangling resource references even after they are deleted.
