### ISSUE TITLE
View "ports" don't work correctly for older versions of GM (+patch)

### ISSUE THREAD

**Issue by sorlok** [IsmAvatar/LateralGM#127]
Currently, LGM will check if it's loading a version of GM that uses view "ports" (destination rectangles for views), and will skip loading those properties if the version is too old. This leads to a bug when loading older GMs, whereby the view is "squished" into the default port size of 640x480. This patch fixes this by setting the "port" size equal to the "view" size if older GM format are being used. 

Patch:
http://pastebin.com/gkqmk1kY

**Comment by RobertBColton** [comment]
For reference, old GM versions can be obtained on this website.
http://bentibbetts.net/animo/

I downloaded GM5 and set the view size to a unique one, 666x666, and exported it as a GMD. I then loaded that GMD into LGMb4/b5, LGM had the right size but the default 640x480 for the port. I then tested GM8.1 and it did what sorlok's patch does. So this verifies the correctness of this patch, and it will be applied in b5 as well.
