### ISSUE TITLE
Bug when saving gmx files

### ISSUE THREAD

**Issue by egofree71** [IsmAvatar/LateralGM#137]
In gmx files, GM Studio saves also the id in the instance's name. LateralGm saves only the string 'inst_'. This will cause a bug if you read this file with GM Studio. I added the instance id in the name : 
inselement.setAttribute("name","inst_" + Integer.toString(in.getID()));

This modification will come with my next pull request.

**Comment by RobertBColton** [comment]
This was actually not the case, instance names are like logical id's, like how you can rename entities in Unity3D. Then you can refer to them by name in scripts. The user is also free to rename them. So the solution I went with in master was to keep and save the instance names and automatically generate new id's for tiles and instances when loading a GMX.
