### ISSUE TITLE
Closing LGM Asks to save changes that I already saved

### ISSUE THREAD

**Issue by IsmAvatar** [IsmAvatar/LateralGM#152]
Steps to reproduce:
- Open LGM
- Open Game Settings
- Make a change (I toggled "Start in fullscreen mode"
- Save Game Settings
- Save the game (take all defaults, give it a name)
- Attempt to Close LGM

Observed behavior: Asks to save, even though nothing has changed since my last save.
Expected behavior: LGM quietly complies and closes.

**Comment by RobertBColton** [comment]
This could be further mitigated by the proposal on #178 I just made when I closed the issue. The final backup preference remaining to be implemented is `backupExit` which would be tied directly to the unsaved changes dialog. If you opt into this, it won't ask you at all, and will just always try to save the project, unless it doesn't have a location, in which case it presents you a file dialog first.
![Ask Save Changes on Exit](https://user-images.githubusercontent.com/3212801/87256180-70672800-c45e-11ea-84ae-e70ad994164f.png)
