### ISSUE TITLE
Feature: Built-in (non-sprite) room-editor icons

### ISSUE THREAD

**Issue by JoshDreamland** [IsmAvatar/LateralGM#167]
An extremely common use case of the room editor is placing control objects that don't have sprites. Dr. Overmars creates sprites with such novelties as old ('90s) computers for this purpose. These sprites are then bundled into his game. This is wasteful, time consuming, and kind of lame.

A feature that would give LGM the edge is allowing an object to have a built-in sprite for these purposes. Right now, objects which do not have sprites are rendered in the room editor using the object sprite (normally a simple ball). I am suggesting a larger palette which can be assigned from in each object.

Essentially, we allow users could pick from a small palette of common icons, such as our script icon. Here are some other considerations:
- Simple `×` icon and `+` icon (for points)
- NE/NW/SE/SW box art for denoting regions
- N/E/S/W/NE/SE/NW/SW arrows, for denoting directional control objects
- NS/EW/NESW/NWSE arrows (see Windows resize and move cursors)
- Compass rose arrows (`×`, `+`, `✳`)
- The iconic "HELP" question mark
- The iconic "ACTION" exclamation point
- A simple text page, for generic messages
- Special-interest icons
  - Iconic brick wall
  - Iconic lock / key
  - Iconic bush / plant / tree
  - Iconic bomb
  - Iconic drop target / targeting reticle
  - Iconic switch / lever
- Probably a hundred other icons I can't currently think of.

These would have to be saved and used exclusively with the GMX and EGM formats. That said, I believe this functionality is central to LateralGM rather than ENIGMA. If keeping a journal of these in the LGM preferences is what is required, then I recommend doing so.

Other room annotations are on the ENIGMA to-do list and may not qualify as part of LGM.

**Comment by RobertBColton** [comment]
@IsmAvatar My apologies, I was definitely ranting when I posted that.

After reviewing Josh's request I actually think this is a semi-good idea. I can't really think of how this has been solved elsewhere before, such as Unity3D or Construct.

Two ideas I can think of as alternatives to what he proposes:
* Allow marking sprites as not being exported to certain target platforms or just not being exported in general. This was something I always like in an IDE and Visual Studio is really the only IDE that gives you the ability to control what is exported to the output directory, copying and pasting files with Qt projects is annoying to get them into the bin directory after a build. LGM could actually implement this through its plugin with no changes to ENIGMA, it could simple pass an empty 1x1px sprite for these flagged resources, or it could basically not pass it at all and nullify any places its used, such as objects that reference it. Or the flag could just be added to the objects "do not export sprite" etc.
* A simpler solution would be to use a separate sprite in place of persistent objects. Controller objects are typically persistent and exist throughout the entire game, I always made them persistent. I am unsure of the degree to which we need the entire selection range as @JoshDreamland proposes.

**Comment by RobertBColton** [comment]
This is a great idea, but let's shelve it for other editor projects.

* Lack of GM format serialization support
* Storing it in the registry preferences doesn't lend itself to revision control
* This idea is right up there with custom room editor rendering

A better iteration on this would be to just allow any Unicode code point/emoji to be used as an editor sprite.
