### ISSUE TITLE
Feature: Constants support

### ISSUE THREAD

**Issue by sorlok** [IsmAvatar/LateralGM#168]
I'm a bit confused by the state of Constants in LGM. It seems that none of the GM\* formats (nor EGM) support saving/loading constants (although the "save to file" works). However, if constants are manually entered into the Constants table, these values _are_ passed along to the compiler. (Note: In parallel, I'm working on getting Constants from the compiler to the game engine, but that's unrelated.) 

How much work is needed to hook up constants parsing in the GM\* and EGM formats to the Constants table in Lateral GM?

**Comment by RobertBColton** [comment]
I am going to close this one out for several reasons.

The EGM aspect of this was already filed over on the lgmplugin. It was resolved when we disabled the old EGM to replace it with the new CI tested version.
https://github.com/enigma-dev/lgmplugin/issues/29

LGM's GMK has supported constants for quite a while and they work beautifully, plus a few tweaks I mention below. LGM's GMX has always written default and config constants and as of 4b5f553efbbfeb1a7a3723c08f3f54cd51d4d6b3 properly reads them back too.

* GMSv1.4 does not read constants from GMD.
* GMSv1.4 reads GM7 GMK constants into the All Configurations global constants.
* GMSv1.4
