### ISSUE TITLE
Tiles are not imported correctly from a GM project

### ISSUE THREAD

**Issue by egofree71** [IsmAvatar/LateralGM#175]
If you open a gmx project with LateralGM, when you save the project, it will set always the following constant for the tile's name : inst_.

If you try to open the project again with GM studio, you will get an exception. This is because it needs an ID. GM studio puts an alpha-numeric id, but it works fine with Enigma Id. (For instance : name="inst_10000002"). This is the same solution used for instances.

There is also another problem : it's not possible to move imported tiles with LateralGM. I've found that's because the depth in GM studio is set by default to 1000000. If you set the value to zero, it's possible to move again tiles.

**Comment by RobertBColton** [comment]
Just to further comment on this ticket. This is now fully resolved in master because I add the name properties to the GMX reader/writer. It also automatically creates id's for tiles/instances even though GMX does not save those. It is useful for downgrading a GMX to GMK.
