### ISSUE TITLE
Saving imported GMX projects as GMK leaves incompatible "Extensions" artifact.

### ISSUE THREAD

**Issue by BPzeBanshee** [IsmAvatar/LateralGM#198]
In my testing of another bug I accidentally encountered this issue that I'm told is strictly LateralGM-land. A picture tells a thousand words so here's a screenshot:
![test1](https://cloud.githubusercontent.com/assets/10321244/5560670/343f6d52-8de5-11e4-8a3c-6e13b07f65c9.png)

To be precise, the Extension Packages has become a non-usable folder called "Extensions" and "Timelines" is written differently from Game Maker 8.0 Pro's default GMK output "Time Lines".

I replicated this issue by:
1) importing and old GMK into Studio OR creating a new project in Studio v1.4.199
2) opening the resulting GMX project in LateralGM (at this point you'll notice there's Extension Packages and also the Extensions folder)
3) saving as a GMK
4) opening said GMK in Game Maker 8.0 Pro

**Comment by RobertBColton** [comment]
For clarity, here is what GM8.1 and GM8.0 are supposed to look like.
![GM 8.0 Tree](https://user-images.githubusercontent.com/3212801/58051658-ca04e880-7b20-11e9-8972-09a3b2b00e05.png)

**Comment by RobertBColton** [comment]
Closing as resolved by #428.
