### ISSUE TITLE
Making subimages less than 5 pixels wide/high causes errors/crash

### ISSUE THREAD

**Issue by BPzeBanshee** [IsmAvatar/LateralGM#199]
Reproduced simply by
1) opening LateralGM
2) creating a new sprite
3) pressing 'add subimage'
3) entering a size less than 5 for either width or height

Error log below (this appears multiple times depending on how long I keep the window open):
http://pastebin.com/RUqNWtT1

**Comment by RobertBColton** [comment]
@BPzeBanshee I've confirmed and reproduced the bug. It is in the painting of the background for an image previewer that is causing this exception, it has to do with the checkered background you see for images. I have them set to fixed block sizes of 5 which the image width/height is divided by. Easy to fix but I need time to see what is the best way to fix it.

**Comment by RobertBColton** [comment]
This is fixed in master, the new release will be made available soon.
