### ISSUE TITLE
Recent Files from CMD Line

### ISSUE THREAD

**Issue by x64L** [IsmAvatar/LateralGM#210]
Hi.
Everytime I open your program I get an error.
Please fix it.
Here is the error log:

Operating System: Windows 7
Version: 6.1
Architecture: amd64

Java Vendor: Oracle Corporation
Version: 1.8.0_25

Available processors (cores): 4
Free memory (bytes): 194256904
Maximum memory (bytes): 932184064
Total memory available to JVM (bytes): 257425408

File system root: C:\
Total space (bytes): 1000097181696
Free space (bytes): 592034275328
Usable space (bytes): 592034275328

File system root: D:\
Total space (bytes): 596865024
Free space (bytes): 0
Usable space (bytes): 0

File system root: E:\
Total space (bytes): 31981993984
Free space (bytes): 29169713152
Usable space (bytes): 29169713152

File system root: F:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

Stack trace:
java.net.URISyntaxException: Illegal character in opaque part at index 2: C:\Users\ThebluemiX\Downloads\3D First.gmk
	at java.net.URI$Parser.fail(Unknown Source)
	at java.net.URI$Parser.checkChars(Unknown Source)
	at java.net.URI$Parser.parse(Unknown Source)
	at java.net.URI.<init>(Unknown Source)
	at org.lateralgm.components.GmMenuBar.updateRecentFiles(GmMenuBar.java:86)
	at org.lateralgm.components.GmMenuBar.<init>(GmMenuBar.java:143)
	at org.lateralgm.main.LGM.main(LGM.java:2343)

java.lang.IllegalStateException: no splash screen available
	at java.awt.SplashScreen.checkVisible(Unknown Source)
	at java.awt.SplashScreen.update(Unknown Source)
	at org.lateralgm.main.LGM$SplashProgress.update(LGM.java:2851)
	at org.lateralgm.main.LGM$SplashProgress.progress(LGM.java:2844)
	at org.lateralgm.main.LGM.main(LGM.java:2349)

**Comment by RobertBColton** [comment]
@ThebluemiX Hello, the issue is that we no longer support Java 6. We also do not support a 64bit Java, you will need to upgrade to the latest 32bit Java installation. You can install the updated Java version in parallel with the old version but you may need to explicitly specify the Java version you wish to run LateralGM with, on windows you can change this in settings.ini, as I have done because I have multiple Java versions in parallel. This is the command I use to force LGM to run in 32bit Java 8.
```ini
idecommand="C:\Program Files (x86)\Java\jre1.8.0_25\bin\java.exe -jar -Xms256m -Xmx1000m"
```
You can download a compatible Java from Oracle.
https://java.com/en/download/

**Comment by ThebluemiX** [comment]
Thanks!

**Comment by ThebluemiX** [comment]
Hi, It's me again.
I installed the latest 32 Bits Java version, and I still get this error.
any ideas?

2015-01-02 10:15 GMT+02:00 Gal Mann <manngal2001@gmail.com>:

**Comment by RobertBColton** [comment]
@ThebluemiX I see, have you also had LateralGM previously installed? i am actually wondering what continues to cause this error.

Try opening the regedit.exe Windows program and navigate to HKEY_CURRENT_USER\Software\JavaSoft\Prefs\org\lateralgm and give me the value of /F/I/L/E_/R/E/C/E/N/T

Once you post it here, go ahead and remove the value from the registry and restart LGM, but make sure you copy the value to me first. Also please elaborate on how you encountered this issue, was this the first time you have run the program or were you doing something different? Exactly what were you doing when you encountered the bug.

**Comment by ThebluemiX** [comment]
Yes, I have the LateralGM jar file, and i managed to run it, but I can't
compile or play my games...
Anyway, here's the value:
I will send you the value in a couple of minutes.
By the way, thank you for the answering so quick.
בתאריך 3 בינו 2015 05:27, ‏"Robert B Colton" <notifications@github.com> כתב:

**Comment by ThebluemiX** [comment]
Here's the value:
/C%3/A%5/C/Users%5/C/Thebluemi/X%5/C/Downloads%5/C3/D+/First.gmk
(I wrote heres the value in my privious letter by accident...)
regards, ThebluemiX

2015-01-03 9:13 GMT+02:00 Gal Mann <manngal2001@gmail.com>:

**Comment by RobertBColton** [comment]
@ThebluemiX Yeah that's not correct, look at mine. Just delete it in the registry and restart LGM and the Recent Files should be reset.
```
file%3/A%2/F/C%3/A%2/F/Users%2/F/Owner%2/F/Desktop%2/F/G/M/Games%2/Ffps%2/F/G/M%2520/Tutorial%2520-%2520/First%2520/Person%2520/Shooter%2/F/Examples%2/Ffps6.gmk file%3/A%2/F/C%3/A%2/F/Users%2/F/Owner%2/F/Desktop%2/F/G/M/Games%2/Fcollisionmemleak.gm81 file%3/A%2/F/C%3/A%2/F/Users%2/F/Owner%2/F/Desktop%2/F/Project/Mario%2/Feditable.gm81 file%3/A%2/F/C%3/A%2/F/Users%2/F/Owner%2/F/Desktop%2/Fproject%2520chaos.gm81 file%3/A%2/F/C%3/A%2/F/Users%2/F/Owner%2/F/Desktop%2/Ftest_exit.gm81 file%3/A%2/F/C%3/A%2/F/Users%2/F/Owner%2/F/Desktop%2/F/Project16.egm file%3/A%2/F/C%3/A%2/F/Users%2/F/Owner%2/F/Desktop%2/F/E/N/I/G/M/A%2/Fenigma-dev%2/F/Users/Owner/Desktop/Project16.egm file%3/A%2/F/C%3/A%2/F/Users%2/F/Owner%2/F/Desktop%2/F/Project16.gmx%2/F/Project16.project.gmx file%3/A%2/F/C%3/A%2/F/Users%2/F/Owner%2/F/Desktop%2/F/Project16.gm81 file%3/A%2/F/C%3/A%2/F/Users%2/F/Owner%2/F/Documents%2/F/Game/Maker%2/F/Projects%2/F/Project16.gmx%2/F/Project16.project.gmx
```

**Comment by ThebluemiX** [comment]
Okay, I'll try that. Thanks!
בתאריך 3 בינו 2015 09:50, ‏"Robert B Colton" <notifications@github.com> כתב:

**Comment by IsmAvatar** [comment]
Robert, LGM used to print out the java version at startup and if it was 1.5 would give you a compatability warning. Since we've dropped 1.6 support, we should recycle that to perhaps display an error to the effect, if possible. That way we don't have to debug obscure stack traces when that's the case.

**Comment by RobertBColton** [comment]
@IsmAvatar I didn't remove it, it still exists but I did update it to 1600 it needs updated again.
https://github.com/IsmAvatar/LateralGM/blob/master/org/lateralgm/main/LGM.java#L2161
