### ISSUE TITLE
LateralGM crashes on game compile.

### ISSUE THREAD

**Issue by rorybg** [IsmAvatar/LateralGM#221]
So LateralGM keeps crashing with this message when I try to compile my game:
Restarting it doesn't seem to help. However making a new blank game with just a room causes no crashes.

Operating System: Windows 8.1
Version: 6.3
Architecture: x86

Java Vendor: Oracle Corporation
Version: 1.8.0_31

Available processors (cores): 4
Free memory (bytes): 212019776
Maximum memory (bytes): 1013645312
Total memory available to JVM (bytes): 259522560

File system root: C:\
Total space (bytes): 948908847104
Free space (bytes): 271032102912
Usable space (bytes): 271032102912

File system root: D:\
Total space (bytes): 26843541504
Free space (bytes): 23842299904
Usable space (bytes): 23842299904

File system root: F:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

File system root: H:\
Total space (bytes): 15539896320
Free space (bytes): 15530426368
Usable space (bytes): 15530426368

Stack trace:

java.lang.Error: Invalid memory access
	at com.sun.jna.Native.invokeInt(Native Method)
	at com.sun.jna.Function.invoke(Function.java:383)
	at com.sun.jna.Function.invoke(Function.java:315)
	at com.sun.jna.Library$Handler.invoke(Library.java:212)
	at com.sun.proxy.$Proxy0.compileEGMf(Unknown Source)
	at org.enigma.EnigmaRunner$CompilerThread.run(EnigmaRunner.java:671)

**Comment by JoshDreamland** [comment]
Hi there,

Please post this on the [ENIGMA tracker](https://github.com/enigma-dev/enigma-dev/issues/), as it's the ENIGMA library that crashed the editor. Also, could you post the game, or a simplified version of the game that still exhibits the error? If you post a copy of your game with as many resources deleted as possible while still maintaining the crash, it makes it simpler for us to figure out what's wrong, as well as keeping your other resources private. Chances are, there's one font with no glyphs, or one sprite with no content (though I'm fairly certain we check for these), or one piece of code that gives the compiler indigestion.

There's just not enough information in that backtrace to figure out what's wrong. The core dump might help, but only so much unless you've built your compiler with debug symbols. Even then, though, we'd probably need an example. If you can't provide the game in either form, please provide a core dump from a debug-enabled compiler.

@TheExDeus: Are you following this tracker? It's relatively low-traffic.

Cheers

**Comment by TheExDeus** [comment]
Yeah, it looks like some resource is messed up. I don't actually think LGM or the plugin checks for anything. It trows an exception even if cannot find settings.ey. So basically LGM and the plugin lacks any kind of checks for anything.

And yes, I do follow this tracker.

**Comment by JoshDreamland** [comment]
Not surprising, but the ENIGMA compiler itself should also do sanity checking on the input, reporting errors if something's amiss. Compiler crashes bring down the entire IDE, so users can lose data from these crashes.

**Comment by rorybg** [comment]
Placed updated Issue on the Enigma tracker as requested: https://github.com/enigma-dev/enigma-dev/issues/946

**Comment by RobertBColton** [comment]
@rorybg Thank you, I will be closing this issue as it is unrelated to LateralGM itself. The issue can be resolved through ENIGMA's tracker which deals with the engine/compiling.
