### ISSUE TITLE
When a custom code editor is defined you have to click 'edit' to edit it in the custom code editor

### ISSUE THREAD

**Issue by faissaloo** [IsmAvatar/LateralGM#254]
This doesn't make any sense, after I've defined a custom code editor I think I've made it pretty obvious that I don't want to use lateralGM's built in editor so I have no idea why it opens lateralGM's built in editor and then makes me click 'edit', it's a pointless step and should really be fixed.

**Comment by RobertBColton** [comment]
@faissaloo Yes, but the reason it does this is because GM8.1 and GMS both do so as well. It is not consistent with the rest of the editors. It is however possible to consider changing the behavior in LGM if you would like to do so. Would you?

**Comment by RobertBColton** [comment]
I am closing this because it's a bit of a duplicate, I have a ticket which scopes for all of this plus the context menu options to open in a system editor. See #102
