### ISSUE TITLE
LGM Crashes When Action is Added

### ISSUE THREAD

**Issue by ryanisaacg** [IsmAvatar/LateralGM#258]
I installed enigma on my Ubuntu GNOME laptop using the instructions at [the enigma site](http://enigma-dev.org/docs/Wiki/Install:Linux). Everything seemed to be going well, until I tried to use it. I launched LGM with the command `java -Djna.nosys=true -jar lateralgm.jar`, and it opened fine. When I created an object, I tried to add an action to the creation event. The entire window froze and refused to respond to input, and wouldn't even close when I hit the close button. I had to close it by killing the process.

**Comment by RobertBColton** [comment]
@ryanisaacg Can I see the results of java -version please? Can you tell me if you installed OpenJDK? If so, Swing applications are practically unusable in OpenJDK, you should instead install the Oracle JDK.

**Comment by ryanisaacg** [comment]
It works fine in Oracle JDK, thanks!

**Comment by RobertBColton** [comment]
@ryanisaacg Sorry about that, but it's really not our fault. The general consensus is that OpenJDK is just really buggy. I am convinced it's haunted with ghosts :smiley: 

I've also updated our download page to recommend the use of Oracle JDK.
http://enigma-dev.org/docs/wiki/index.php?title=Install&action=historysubmit&diff=30805&oldid=30735
