### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by AwesomeAs** [IsmAvatar/LateralGM#280]
Operating System: Windows 10
Version: 10.0
Architecture: amd64

Java Name: Java HotSpot(TM) 64-Bit Server VM
Java Vendor: Oracle Corporation
Version: 1.8.0_91

Available processors (cores): 8
Free memory (bytes): 194836208
Maximum memory (bytes): 3799515136
Total memory available to JVM (bytes): 218628096

File system root: C:\
Total space (bytes): 954339422208
Free space (bytes): 785061695488
Usable space (bytes): 785061695488

File system root: D:\
Total space (bytes): 26843541504
Free space (bytes): 23818821632
Usable space (bytes): 23818821632

Stack trace:
org.lateralgm.file.GmFormatException: java.io.IOException: Cannot run program "mingw32-make.exe" (in directory "C:\Users\Andreas\Documents\GMMailmanTurbo\enigma-dev-master"): CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.enigma.EnigmaRunner.make(EnigmaRunner.java:308)
	at org.enigma.EnigmaRunner$3.run(EnigmaRunner.java:173)

**Comment by faissaloo** [comment]
Have you installed MinGW? On Windows you need to install MinGW to use Enigma.

**Comment by RobertBColton** [comment]
ENIGMA does not currently support 64 bit Java on Windows. You will need to install a 32 bit Java and change the settings file. Please see the following article on our Wiki.
http://enigma-dev.org/docs/Wiki/Install:Parallel_Java

**Comment by AwesomeAs** [comment]
I ended up writing a .obj to .d3d converter in Java the same day (just parses the .obj file and creates a file with structure "100
operation count
operation id    parameters...
operation id    parameters...
etc"). Works for my needs, and with the hacky way of having an object to load and render a d3d model, I can draw the model with colors. Only lacks shading and material textures now.

Anyways, thanks for the quick response. Game Maker sure is one hell of uncompability and scarce on resources.

**Comment by RobertBColton** [comment]
You're very welcome, please let us know if you anymore problems!
