### ISSUE TITLE
how to change the code editor font ?

### ISSUE THREAD

**Issue by dazzulay** [IsmAvatar/LateralGM#325]
this is shotscreen [http://i.imgur.com/tXh0y5G.png](http://i.imgur.com/tXh0y5G.png)
it was too small, i want to change the font size and font.

**Comment by Hughtech** [comment]
I have found a solution to your problem. It is possible to override the settings of ENIGMA. I have done such a thing and thus made a video which you can see on my YouTube channel using this link:

[https://youtu.be/lNPmiXRqVM0](url)

I am using the LINUX version on MX LINUX 16. You did not mention which version and what OS you have, so I'm not sure if it will work on Windows,  I don't have a Mac so I can help you if you're using on. You can check out this link here however for some insights 

[http://enigma-dev.org/docs/Wiki/Overriding_settings](url).

Hope this was able to you out.
