### ISSUE TITLE
Font editor UX is confusing

### ISSUE THREAD

**Issue by JoshDreamland** [IsmAvatar/LateralGM#329]
Make the purpose of the "Character range" box clearer.

1. Move it under the range list so it doesn't get mixed in with the list editing buttons
2. Eliminate its lame duck state (where your input is completely ignored) by doing one of these:
   1. Disable it (gray it out) by default, enabling it once a range is selected.
   2. Add a default range (eg, letters) and select it by default so that editing the boxes is meaningful.
   3. Make the "Add Range" ` + ` button actually respect the range you've entered in the box, and move that button next to the input boxes. I discourage this as it still leaves the possibility of your input being ignored, and makes the function of the input boxes ambiguous (now you have to clone before editing).

**Comment by RobertBColton** [comment]
Your concerns were addressed by #412 which includes #388.

**Comment by RobertBColton** [comment]
Closing as finally resolved #413.
