### ISSUE TITLE
still no answer

### ISSUE THREAD

**Issue by RemoveRusky** [IsmAvatar/LateralGM#360]
#355 #352

**Comment by JoshDreamland** [comment]
You two are generating a metric shitton of mail. Cheeseboy, please stop harassing Robert. Robert, please stop releasing LGM after every commit.

**Comment by RemoveRusky** [comment]
I needa ask this nigger shit bout his ide but hes hiding like a bitch. I'll bug him till I get answers one way or another

**Comment by RobertBColton** [comment]
That's nice you big whale sperm you. Please no cussing on the tracker. And Josh, please don't be selling bitcoin on this tracker.

My reply:
https://github.com/enigma-dev/RadialGM/pull/12
