### ISSUE TITLE
Enigma cannot run because it does not recognize your Platform, or deosnt have 'make' definition

### ISSUE THREAD

**Issue by zykloner** [IsmAvatar/LateralGM#411]
LateralGM Version: 1.8.53

Operating System: Linux
Version: 4.4.0-53-generic
Architecture: amd64

Java Name: OpenJDK 64-Bit Server VM
Java Vendor: Oracle Corporation
Version: 1.8.0_191

Available processors (cores): 4
Free memory (bytes): 86646312
Maximum memory (bytes): 894959616
Total memory available to JVM (bytes): 115867648

File system root: /
Total space (bytes): 504641847296
Free space (bytes): 197871263744
Usable space (bytes): 172213346304

Stack trace:
org.lateralgm.file.GmFormatException: java.lang.IndexOutOfBoundsException: Make-Vars
	at org.enigma.file.YamlParser$YamlNode.getM(YamlParser.java:61)
	at org.enigma.EnigmaRunner.make(EnigmaRunner.java:279)
	at org.enigma.EnigmaRunner$3.run(EnigmaRunner.java:174)

**Comment by RobertBColton** [comment]
* Please make sure to `git pull` to update ENIGMA. This may require a `make clean` and `make` to clean build the backend.
* Make sure you have the latest version of the ENIGMA plugin (there were changes to it regarding `Make-Vars` by myself)
https://github.com/enigma-dev/lgmplugin/releases/tag/v1.8.7.11r3

**Comment by RobertBColton** [comment]
Automatically closing as that should have resolved the issue. If you need additional help with something else feel free to post a new issue, ask on the forums, or join the Discord server.
