### ISSUE TITLE
background_blend error

### ISSUE THREAD

**Issue by BeepBoop486** [IsmAvatar/LateralGM#458]
[g++] SHELLmain.cpp
n ‘[01m[Kvariant roomcreate2()[m[K’:
[01m[K/home/nothers/.enigma/Preprocessor_Environment_Editable/IDE_EDIT_roomcreates.h:124:3:[m[K [01;31m[Kerror: [m[K‘[01m[Kbackground_blend[m[K’ was not declared in this scope
   [01;31m[Kbackground_blend[m[K[int(0)]= c_blue;
   [01;31m[K^~~~~~~~~~~~~~~~[m[K
n ‘[01m[Kvariant roomcreate2()[m[K’:
[01m[K/home/nothers/.enigma/Preprocessor_Environment_Editable/IDE_EDIT_roomcreates.h:124:3:[m[K [01;31m[Kerror: [m[K‘[01m[Kbackground_blend[m[K’ was not declared in this scope
   [01;31m[Kbackground_blend[m[K[int(0)]= c_blue;
   [01;31m[K^~~~~~~~~~~~~~~~[m[K
n ‘[01m[Kvariant roomcreate2()[m[K’:
[01m[K/home/nothers/.enigma/Preprocessor_Environment_Editable/IDE_EDIT_roomcreates.h:124:3:[m[K [01;31m[Kerror: [m[K‘[01m[Kbackground_blend[m[K’ was not declared in this scope
   [01;31m[Kbackground_blend[m[K[int(0)]= c_blue;
   [01;31m[K^~~~~~~~~~~~~~~~[m[K
n ‘[01m[Kvariant roomcreate2()[m[K’:
[01m[K/home/nothers/.enigma/Preprocessor_Environment_Editable/IDE_EDIT_roomcreates.h:124:3:[m[K [01;31m[Kerror: [m[K‘[01m[Kbackground_blend[m[K’ was not declared in this scope
   [01;31m[Kbackground_blend[m[K[int(0)]= c_blue;
   [01;31m[K^~~~~~~~~~~~~~~~[m[K
In file included from [01m[KSHELLmain.cpp:106[m[K:
[01m[K/home/nothers/.enigma/Preprocessor_Environment_Editable/IDE_EDIT_roomcreates.h:[m[K In function ‘[01m[Kvariant roomcreate2()[m[K’:
[01m[K/home/nothers/.enigma/Preprocessor_Environment_Editable/IDE_EDIT_roomcreates.h:124:3:[m[K [01;31m[Kerror: [m[K‘[01m[Kbackground_blend[m[K’ was not declared in this scope
   [01;31m[Kbackground_blend[m[K[int(0)]= c_blue;
   [01;31m[K^~~~~~~~~~~~~~~~[m[K
make[1]: *** [Makefile:177: /home/nothers/.enigma/.eobjs/Linux/Linux/GNU_GCC_G++/Run/SHELLmain.o] Error 1
make[1]: se sale del directorio '/home/nothers/enigma-dev/ENIGMAsystem/SHELL'
make: *** [Makefile:22: Game] Error 2
make[1]: *** [Makefile:177: /home/nothers/.enigma/.eobjs/Linux/Linux/GNU_GCC_G++/Run/SHELLmain.o] Error 1
make[1]: se sale del directorio '/home/nothers/enigma-dev/ENIGMAsystem/SHELL'
make: *** [Makefile:22: Game] Error 2
make[1]: *** [Makefile:177: /home/nothers/.enigma/.eobjs/Linux/Linux/GNU_GCC_G++/Run/SHELLmain.o] Error 1
make[1]: se sale del directorio '/home/nothers/enigma-dev/ENIGMAsystem/SHELL'
make: *** [Makefile:22: Game] Error 2
make[1]: *** [Makefile:177: /home/nothers/.enigma/.eobjs/Linux/Linux/GNU_GCC_G++/Run/SHELLmain.o] Error 1
make[1]: se sale del directorio '/home/nothers/enigma-dev/ENIGMAsystem/SHELL'
make: *** [Makefile:22: Game] Error 2
make[1]: *** [Makefile:177: /home/nothers/.enigma/.eobjs/Linux/Linux/GNU_GCC_G++/Run/SHELLmain.o] Error 1
make[1]: se sale del directorio '/home/nothers/enigma-dev/ENIGMAsystem/SHELL'
make: *** [Makefile:22: Game] Error 2

**Comment by RobertBColton** [comment]
Wrong tracker, please file this on the ENIGMA repo.
https://github.com/enigma-dev/enigma-dev/issues
