### ISSUE TITLE
So LateralGM with Enigma won't start.

### ISSUE THREAD

**Issue by RadThadd** [IsmAvatar/LateralGM#464]
### LateralGM freshly downloaded alone works fine. I just NEED the runner/exporter too :skull: 
--------------------------

LateralGM Version: 1.8.89
Working Directory: C:\enigma-dev-master\lateralgm.jar

Operating System: Windows 8.1
Version: 6.3
Architecture: amd64

Java Name: Java HotSpot(TM) 64-Bit Server VM
Java Vendor: Oracle Corporation
Version: 11.0.1

Current Thread: main
Available processors (cores): 4
Free memory (bytes): 39044608
Maximum memory (bytes): 1046478848
Total memory available to JVM (bytes): 67108864

File system root: C:\
Total space (bytes): 781966110720
Free space (bytes): 140759838720
Usable space (bytes): 140759838720

Stack trace:
java.lang.NoClassDefFoundError: com/sun/jna/Pointer
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3138)
	at java.base/java.lang.Class.getConstructor0(Class.java:3343)
	at java.base/java.lang.Class.newInstance(Class.java:556)
	at org.lateralgm.main.LGM.loadPlugins(LGM.java:705)
	at org.lateralgm.main.LGM.main(LGM.java:1167)
Caused by: java.lang.ClassNotFoundException: com.sun.jna.Pointer
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 6 more

**Comment by RobertBColton** [comment]
I suspect this is an issue with Java 11. Can you try the following to disable system JNA?
https://enigma-dev.org/docs/Wiki/Troubleshoot#Why_do_I_get_.22Can.27t_obtain_updateLastError.22_when_launching.3F

**Comment by RadThadd** [comment]
> I suspect this is an issue with Java 11. Can you try the following to disable system JNA?
> https://enigma-dev.org/docs/Wiki/Troubleshoot#Why_do_I_get_.22Can.27t_obtain_updateLastError.22_when_launching.3F

Yeah we fixed it bro. But now I just need a copy of the "compileEGMF.dll" because it's giving me the "Unable to load library" message

**Comment by RobertBColton** [comment]
Sorry about that and yeah Josh actually found it, our JNA link was a 404. I've fixed it in 80c286d9284372ed9798eafbcbba8802a09e2849 for others now.

You should manually run `make all` in the enigma-dev folder to fix your next problem.

**Comment by RadThadd** [comment]
> Sorry about that and yeah Josh actually found it, our JNA link was a 404. I've fixed it in [enigma-dev/ExtraPackages@80c286d](https://github.com/enigma-dev/ExtraPackages/commit/80c286d9284372ed9798eafbcbba8802a09e2849) for others now.
> 
> You should manually run `make all` in the enigma-dev folder to fix your next problem.

Great! Problem is, the console gives me that "make[1] g++: Command not found" error, how do I fix this one?

**Comment by RobertBColton** [comment]
Did you not install GCC?

**Comment by JoshDreamland** [comment]
The install script (install.sh) should have warned that JNA wasn't available, and should have installed GCC for you. Do you have the output from when you ran it?

**Comment by RadThadd** [comment]
> 
> 
> The install script (install.sh) should have warned that JNA wasn't available, and should have installed GCC for you. Do you have the output from when you ran it?

The JNA is okay now thanks you guys. But i'm using Cygwin to install gcc because it's simpler I think. Anyway, once Cygwin finishes, how do I install it in Msys2? or do I even have to?

**Comment by RadThadd** [comment]
> The install script (install.sh) should have warned that JNA wasn't available, and should have installed GCC for you. Do you have the output f

**Comment by RadThadd** [comment]
Okay dudes, tbh I didn't know what the hell I was doing. But the issue is fixed. BUT there is a technical issue, where I cannot click anything on my screen after LateralGM starts up.

**Comment by RobertBColton** [comment]
If you try the latest release that may have been fixed by #506 where the main frame was previously being created before the EDT. I am going to close this one for now until somebody reports it again because a lot of changes have been made to improve thread safety now. If it's still happening it could be related to the look and feel or ENIGMA plugin, but feel free to repost.
