### ISSUE TITLE
Custom Look & Feels Broke

### ISSUE THREAD

**Issue by RobertBColton** [IsmAvatar/LateralGM#493]
Setting a custom look and feel as described on the forum no longer works.
https://enigma-dev.org/forums/index.php?topic=2283.0

This was reported by hugar on the enigma-dev tracker originally.
https://github.com/enigma-dev/enigma-dev/issues/2028

I am also able to reproduce it but the exception is only printed, not shown in the standard error dialog.

The issue is caused by the fact that the system class loader is no longer a URLClassLoader which precludes adding the look and feels to the class path at runtime.
https://stackoverflow.com/a/46724308

**Comment by Hughtech** [comment]
Thanks. Version 8 is the default so there should be any problems. This issue came about because I'm using a higher version......version 11 to be exact.

**Comment by RobertBColton** [comment]
Closing as resolved by #494.
