### ISSUE TITLE
backgrounds in room editor doesnt size/tile properly

### ISSUE THREAD

**Issue by Hughtech** [IsmAvatar/LateralGM#520]
### Describe the bug

when game is run, background images are resized smaller and there is a gap.

### Steps To Reproduce

1. Create a background smaller than the size of room
2. Place that background into the room and click on 'Stretch'
3. when game is run, the image will be truncated and black bars around the image....'

### Expected behavior

the background should cover the length of the room

### Game Files & Screenshots

![Screenshot_2020-07-20_20-15-18](https://user-images.githubusercontent.com/19632613/88003278-78643f00-cad2-11ea-94d8-258f6a872f7a.png)

**Comment by RobertBColton** [comment]
Closing this as it's already on the ENIGMA tracker and we're aware of it and fixing it. Thanks for reporting this though hugar!
https://github.com/enigma-dev/enigma-dev/pull/2008
