### ISSUE TITLE
Ubuntu & SDL: gamepad_button_check_XXXX & joystick_check_button Don't Exist 

### ISSUE THREAD

**Issue by mikeypro83** [IsmAvatar/LateralGM#521]
### Describe the bug
On Unbuntu setting my project's playtform to SDL and using any of the gamepad/joysticks functions results in a compile failure of the project and enigma reports the reason is those functions do not exist.

### Steps To Reproduce

1. under linux/unix, set project platform to SDL
2. add code referencing any of the gamepad/joystick functions
3. attempt to run/compile  project

### Expected behavior
compile will fail stating that the joystick/gamepad functions do not exist

### Exceptions & Error Messages
Building for mode (0)
Cleaning up from previous executions
 - Cleared parsed objects
 - Cleared room entries
 - Cleared shared locals list
 - Cleared event info
Loading shared locals from extensions list
Location in memory of structure: 0x7ff968003dc0
Copying resources:
Copying sprite names [16]
Copying sound names [0]
Copying background names [1]
Copying path names [0]
Copying script names [4]
Copying shader names [0]
Copying font names [3]
Copying timeline names [0]
Copying object names [21]
Copying room names [5]
Copying constant names [0]
SYNTAX CHECKING AND PRIMARY PARSING:
4 Scripts:
Parsed `scr_Globals': 0 locals, 0 globals
Parsed `scr_window': 0 locals, 0 globals
Syntax error in script `scr_UpdateMenuButtons'
Line 6, position 24 (absolute 190): Unknown function or script `joystick_check_button'

**Comment by RobertBColton** [comment]
@mikeypro83 ENIGMA engine bugs/compile failures go on the enigma-dev tracker, LGM is just a game maker file editor, it has no concept of "running" a game. Please post this on the correct tracker, thanks!
https://github.com/enigma-dev/enigma-dev
