### ISSUE TITLE
GGS fucked in the hymen breaking open blood right by the pussy

### ISSUE THREAD

**Issue by time-killer-games** [IsmAvatar/LateralGM#524]
global game window-related settings is fucked

https://i.pinimg.com/originals/9e/c2/0a/9ec20afc3abf2d74ac31df0561fca723.jpg

https://github.com/enigma-dev/enigma-dev/issues/2109

**Comment by RobertBColton** [comment]
Closing as resolved in LGM v1.8.184 which is available for download.
https://github.com/IsmAvatar/LateralGM/commit/2bb31d00328c4dea6d341c6152f3760f71543709
https://github.com/IsmAvatar/LateralGM/releases/tag/v1.8.184
