### ISSUE TITLE
Ask for Save

### ISSUE THREAD

**Issue by polygoned** [IsmAvatar/LateralGM#53]
LGM keeps asking to save the file even when it hasn't been changed.

**Comment by RobertBColton** [comment]
This could be further mitigated by the proposal on #178 I just made when I closed the issue. The final backup preference remaining to be implemented is `backupExit` which would be tied directly to the unsaved changes dialog. If you opt into this, it won't ask you at all, and will just always try to save the project, unless it doesn't have a location, in which case it presents you a file dialog first.
![Ask Save Changes on Exit](https://user-images.githubusercontent.com/3212801/87256180-70672800-c45e-11ea-84ae-e70ad994164f.png)
