### ISSUE TITLE
Fonts corrupton when using to display numbers

### ISSUE THREAD

**Issue by Hughtech** [IsmAvatar/LateralGM#552]
### Describe the bug

Fonts being displayed corrupted after the 7th digit. This happens you use the functions font_add_sprite or using a standard font in the Font category to display scores.

### Steps To Reproduce

1. Go to 'Fonts...'
2. Click on 'Add Font....'
3. Use any font
4. Create object
5. in the create event, type score = 1234567890
5. in the Dtaw event type draw_text(x, y, string(score))
6. run the game

### Expected behavior

the score  should be displayed "1234567890' but instead there is "1.234566+09" or something to that effect
![font_corrupted2](https://user-images.githubusercontent.com/19632613/112724927-fe4f4a00-8eeb-11eb-8098-e52ce16ed3e5.png)

### Game Files & Screenshots

![font_corrupted1](https://user-images.githubusercontent.com/19632613/112725010-5a19d300-8eec-11eb-8192-72295dcb80b0.png)
![font_corrupted3_draw_event](https://user-images.githubusercontent.com/19632613/112725376-48392f80-8eee-11eb-9f2f-88a02f83e187.png)

**Comment by RobertBColton** [comment]
This is not a LateralGM bug, you are describing the scientific notation issue in ENIGMA.
https://github.com/enigma-dev/enigma-dev/issues/488
