### ISSUE TITLE
Effect functions not working

### ISSUE THREAD

**Issue by hpgDesigns** [IsmAvatar/LateralGM#558]
### Describe the bug

the functions effect_create_above and effect_create_below are not working now. Whether you use them in code or as drag n drop, the game crashes.

### Steps To Reproduce

1. create a simple sprite
2. create an object using that sprite
3. create a room and place the object in room
4. in the object, create a **Mouse Pressed** event and place the code "instance_destroy()"
5. create a **Destroy** event and place the code "`effect_create_above(ef_explosion, 0, 0, 0, c_blue);`"
6. create a **Draw** event and write code `draw_self()`

### Expected behavior

If all goes well, when you click on the sprite, it should be destroyed followed by an explosion effect.

### Exceptions & Error Messages

the 'game' crashes immediately.

### Game Files & Screenshots

![Screenshot_2021-11-19_03-44-23](https://user-images.githubusercontent.com/75296992/142617710-76a90f2e-b414-46be-b217-8a0c443e589a.png)

**Comment by RobertBColton** [comment]
This is ENIGMA related, nothing to do with the editor.
