### ISSUE TITLE
The system fails to find the specified path (gcc.ey)

### ISSUE THREAD

**Issue by Quarnion** [IsmAvatar/LateralGM#559]
The project has a room, but only the stop button is active. At the first opening, this error came out:

LateralGM Version: 1.8.234
Working Directory: C:\ENIGMA\enigma-dev\lateralgm.jar

Operating System: Windows 7
Version: 6.1
Architecture: amd64

Java Name: Java HotSpot(TM) 64-Bit Server VM
Java Vendor: Oracle Corporation
Version: 16.0.1

Current Thread: Thread-1
Available processors (cores): 4
Free memory (bytes): 17104200
Maximum memory (bytes): 2145386496
Total memory available to JVM (bytes): 37748736

File system root: C:\
Total space (bytes): 499581448192
Free space (bytes): 39524298752
Usable space (bytes): 39524298752

File system root: D:\
Total space (bytes): 320063397888
Free space (bytes): 249962496
Usable space (bytes): 249962496

File system root: E:\
Total space (bytes): 80023121920
Free space (bytes): 700416
Usable space (bytes): 700416

File system root: G:\
Total space (bytes): 31441862656
Free space (bytes): 340180992
Usable space (bytes): 340180992

Stack trace:
org.lateralgm.file.GmFormatException: java.io.FileNotFoundException: Compilers\Windows\gcc.ey (The system fails to find the specified path)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(Unknown Source)
	at java.base/java.io.FileInputStream.<init>(Unknown Source)
	at java.base/java.util.Scanner.<init>(Unknown Source)
	at java.base/java.util.Scanner.<init>(Unknown Source)
	at org.enigma.file.YamlParser.parse(YamlParser.java:189)
	at org.enigma.EnigmaRunner.make(EnigmaRunner.java:281)
	at org.enigma.EnigmaRunner$3.run(EnigmaRunner.java:171)

**Comment by Quarnion** [comment]
![err](https://user-images.githubusercontent.com/37442909/143978234-fd99c24b-4351-4689-931f-9de4c3dc724d.jpg)

**Comment by RobertBColton** [comment]
This is ENIGMA/plugin related, nothing to do here with the editor project.
https://github.com/enigma-dev/lgmplugin
